In [1]:
# 파이토치 모듈
import torch

In [2]:
# 텐서 생성하기
ft = torch.FloatTensor([[1,2],[3,4]])
ft

tensor([[1., 2.],
        [3., 4.]])

In [3]:
# Long 타입 텐서
lt = torch.LongTensor([[1,2],[3,4]])
print(lt)

# Byte 타입 텐서
bt = torch.ByteTensor([[1,0],[0,1]])
print(bt)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 0],
        [0, 1]], dtype=torch.uint8)


In [5]:
import numpy as np

# 파이토치는 Numpy와 호환이 가능하다.
x = np.array([[1,2],[3,4]]) # Define numpy array.
print(x,type(x))

x = torch.from_numpy(x)
print(x,type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>
tensor([[1, 2],
        [3, 4]], dtype=torch.int32) <class 'torch.Tensor'>


In [6]:
# Tensor -> numpy로 변환
x = x.numpy()
print(x,type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [7]:
# Tensor 타입 변환하기
print(ft.long())
print(ft.float())

tensor([[1, 2],
        [3, 4]])
tensor([[1., 2.],
        [3., 4.]])


In [12]:
x = torch.FloatTensor([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])

print(x.size())
print(x.shape)

print("\n")
print(x.size(1))
print(x.shape[1])

print("\n")
print(x.size(-1))
print(x.shape[-1])

print("\n")
print(x.dim())
print(len(x.size()))

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


2
2


2
2


3
3


In [13]:
# pytorch 연산
a = torch.FloatTensor([[1,2],[3,4]])
b = torch.FloatTensor([[2,2],[3,3]])

# 산술 연산
print(a + b)
print(a - b)
print(a * b)
print(a / b)

print("\n")

# 제곱 연산
print(a**b)

# 논리 연산
print(a == b)
print(a != b)

tensor([[3., 4.],
        [6., 7.]])
tensor([[-1.,  0.],
        [ 0.,  1.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])


tensor([[ 1.,  4.],
        [27., 64.]])
tensor([[False,  True],
        [ True, False]])
tensor([[ True, False],
        [False,  True]])


In [15]:
# 인플레이스 연산(mul_() 함수)
print(a)

print("\n")
print(a.mul(b))
print(b.mul(a))

tensor([[1., 2.],
        [3., 4.]])


tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])


In [19]:
# 차원 축소 연산: 합과 평균
x = torch.FloatTensor([[1,3],[5,7]])
print(x.sum())

print(x.mean())

tensor(16.)
tensor(4.)


In [21]:
# dim(차원): 연산의 차원
print(x.sum(dim=0)) # [1+5., 3+7.] = [6., 10.]
print(x.sum(dim=1)) # [1+3., 5+7.] = [4., 12.]

tensor([ 6., 10.])
tensor([ 4., 12.])


In [22]:
# 차원의 범위 초과. 즉 2차원 배열을 초과하는 범위이므로 오류!
print(x.sum(dim=2))

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [23]:
print(x.sum(dim=-1)) # [1+3., 5+7.] = [4., 12.] == 1차원 하고 값이 비슷
print(x.sum(dim=-2)) # [1+5., 3+7.] = [6., 10.] == 0차원 하고 값이 비슷

tensor([ 4., 12.])


In [26]:
# 3차원 축소 연산
x = torch.FloatTensor([[[1,3],[5,7]],[[2,4],[6,8]],[[9,10],[11,12]]])

print(x.sum(dim=0)) # [[1+2+9., 3+4+10.], [5+6+11., 7+8+12.]]
print(x.sum(dim=1)) # [[1+5., 3+7.], [2+6., 4+8.], [9+11., 10+12.]]
print(x.sum(dim=2)) # [[1+3., 5+7.], [2+4., 6+8.], [9+10., 11+12.]]

tensor([[12., 17.],
        [22., 27.]])
tensor([[ 6., 10.],
        [ 8., 12.],
        [20., 22.]])
tensor([[ 4., 12.],
        [ 6., 14.],
        [19., 23.]])


In [27]:
# 2차원을 초과하면 에러!
print(x.sum(dim=3))

IndexError: Dimension out of range (expected to be in range of [-3, 2], but got 3)

In [30]:
# 브로드캐스트 연산
# 텐서 + 스칼라
x = torch.FloatTensor([[1,2],[3,4]])
y = 1
z = x + y

print(z)
print(z.size())

tensor([[2., 3.],
        [4., 5.]])
torch.Size([2, 2])


In [31]:
# 텐서 + 벡터
x = torch.FloatTensor([[1,2],[4,8]])
y = torch.FloatTensor([3,5])

print(x.size())
print(y.size())

print("\n")
z = x + y
# [[1,2],  [[3,5],   [[4,7]
# [4,8]] +  [3,5]] =  [7,13]]

print(z)
print(z.size())

torch.Size([2, 2])
torch.Size([2])


tensor([[ 4.,  7.],
        [ 7., 13.]])
torch.Size([2, 2])


In [32]:
x = torch.FloatTensor([[[1,2]]])
y = torch.FloatTensor([3,5])

print(x.size())
print(y.size())

print("\n")
z = x + y
print(z)
print(z.size())

torch.Size([1, 1, 2])
torch.Size([2])


tensor([[[4., 7.]]])
torch.Size([1, 1, 2])


In [33]:
# 텐서 + 텐서
x = torch.FloatTensor([[1,2]])
y = torch.FloatTensor([[3],[5]])

print(x.size())
print(y.size())

print("\n")
z = x + y
print(z)
print(z.size())

torch.Size([1, 2])
torch.Size([2, 1])


tensor([[4., 5.],
        [6., 7.]])
torch.Size([2, 2])
