In [3]:
import torch
import torch.nn.functional as F

In [6]:
target=torch.FloatTensor([[.1,.2,.3],[.4,.5,.6],[.7,.8,.9]])

In [7]:
x=torch.rand_like(target)
x.requires_grad=True
print(x)

tensor([[0.2316, 0.0607, 0.2361],
        [0.3857, 0.5836, 0.8604],
        [0.3771, 0.0152, 0.0278]], requires_grad=True)


In [9]:
loss=F.mse_loss(x,target)
loss

tensor(0.1774, grad_fn=<MseLossBackward0>)

In [11]:
threshold=1e-5
learning_rate=1.
iter_cnt=0

while loss > threshold:
    iter_cnt+=1
    loss.backward()
    
    x=x-learning_rate*x.grad
    
    x.detach_()
    x.requires_grad_(True)
    
    loss=F.mse_loss(x,target)
    
    print('%d-th Loss: %.4e' %(iter_cnt,loss))
    print(x)

1-th Loss: 6.4923e-02
tensor([[0.1796, 0.1157, 0.2614],
        [0.3914, 0.5505, 0.7575],
        [0.5047, 0.3253, 0.3724]], requires_grad=True)
2-th Loss: 3.9274e-02
tensor([[0.1619, 0.1344, 0.2699],
        [0.3933, 0.5393, 0.7225],
        [0.5481, 0.4308, 0.4896]], requires_grad=True)
3-th Loss: 2.3759e-02
tensor([[0.1481, 0.1490, 0.2766],
        [0.3948, 0.5306, 0.6953],
        [0.5818, 0.5128, 0.5808]], requires_grad=True)
4-th Loss: 1.4372e-02
tensor([[0.1374, 0.1603, 0.2818],
        [0.3959, 0.5238, 0.6741],
        [0.6081, 0.5766, 0.6517]], requires_grad=True)
5-th Loss: 8.6944e-03
tensor([[0.1291, 0.1692, 0.2859],
        [0.3968, 0.5185, 0.6576],
        [0.6285, 0.6263, 0.7069]], requires_grad=True)
6-th Loss: 5.2596e-03
tensor([[0.1227, 0.1760, 0.2890],
        [0.3975, 0.5144, 0.6448],
        [0.6444, 0.6649, 0.7498]], requires_grad=True)
7-th Loss: 3.1817e-03
tensor([[0.1176, 0.1813, 0.2914],
        [0.3981, 0.5112, 0.6349],
        [0.6568, 0.6949, 0.7832]], requi