In [1]:
import numpy as np
import torch

In [2]:
# View 함수
x=torch.FloatTensor([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(x.size())

print("\n")
print(x.view(12)) # 12 = 3 * 2 * 2
print(x.view(3, 4)) # 3 * 4 = 3 * 2 * 2
print(x.view(3, 1, 4))

torch.Size([3, 2, 2])


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])


In [3]:
print(x.view(-1))
print(x.view(3,-1))
print(x.view(-1,1,4))

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])


In [6]:
y = x.view(3,4)
x.storage().data_ptr() == y.storage().data_ptr()

True

In [7]:
# Squeeze 함수
x=torch.FloatTensor([[[1,2],[3,4]]])
print(x.size())

print(x.squeeze())
print(x.squeeze().size())

print("\n")
print(x.squeeze(0).size())
print(x.squeeze(1).size())

torch.Size([1, 2, 2])
tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])


torch.Size([2, 2])
torch.Size([1, 2, 2])


In [9]:
# Unsqueeze 함수
x=torch.FloatTensor([[1,2],[3,4]])
print(x.size())

print("\n")
print(x.unsqueeze(1).size())
print(x.unsqueeze(-1).size())
print(x.unsqueeze(2).size())

torch.Size([2, 2])


torch.Size([2, 1, 2])
torch.Size([2, 2, 1])
torch.Size([2, 2, 1])


In [10]:
print(x.reshape(2,2,-1).size())

torch.Size([2, 2, 1])


In [11]:
# Tensor Indexing & Slicing
x=torch.FloatTensor([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(x.size())

print("\n")
print(x[0])
print(x[-1])
print(x[:,0])
print(x[1:2,1:,:].size())

torch.Size([3, 2, 2])


tensor([[1., 2.],
        [3., 4.]])
tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])
torch.Size([1, 1, 2])


In [12]:
# Tensor Split
x=torch.FloatTensor(10,4)
splits=x.split(4,dim=0)

for s in splits:
    print(s.size())

torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


In [13]:
# Tensor Chunk
x=torch.FloatTensor(8,4)
chunks=x.chunk(3,dim=0)

for c in splits:
    print(c.size())

torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


In [15]:
# Index Select 함수
x=torch.FloatTensor([[[1,1],[2,2]],[[3,3],[4,4]],[[5,5],[6,6]]])
indice=torch.LongTensor([2,1])
print(x.size())

y=x.index_select(dim=0,index=indice)
print(y)
print(y.size())

torch.Size([3, 2, 2])
tensor([[[5., 5.],
         [6., 6.]],

        [[3., 3.],
         [4., 4.]]])
torch.Size([2, 2, 2])


In [16]:
x=torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9]])
y=torch.FloatTensor([[10,11,12],[13,14,15],[16,17,18]])

print(x.size(),y.size())

z=torch.cat([x,y],dim=0)
print(z)
print(z.size())

torch.Size([3, 3]) torch.Size([3, 3])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])
torch.Size([6, 3])


In [17]:
z=torch.cat([x,y],dim=-1)
print(z)
print(z.size())

tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]])
torch.Size([3, 6])


In [18]:
z=torch.stack([x,y])
print(z)
print(z.size())

print("\n")
z=torch.stack([x,y],dim=-1)
print(z)
print(z.size())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])


tensor([[[ 1., 10.],
         [ 2., 11.],
         [ 3., 12.]],

        [[ 4., 13.],
         [ 5., 14.],
         [ 6., 15.]],

        [[ 7., 16.],
         [ 8., 17.],
         [ 9., 18.]]])
torch.Size([3, 3, 2])


In [20]:
d=0
z=torch.cat([x.unsqueeze(d),y.unsqueeze(d)],dim=d)
print(z)
print(z.size())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])


In [21]:
# stack 함수의 사용 예
result=[]
for i in range(5):
    x=torch.FloatTensor(2,2)
    result+=[x]

result=torch.stack(result)

print(result)

tensor([[[6.0311e+00, 0.0000e+00],
         [5.6052e-45, 0.0000e+00]],

        [[9.1477e-41, 0.0000e+00],
         [5.0447e-44, 0.0000e+00]],

        [[0.0000e+00, 2.7812e+00],
         [5.6258e-36, 5.7593e-43]],

        [[1.5062e+01, 0.0000e+00],
         [5.6052e-45, 0.0000e+00]],

        [[1.2000e+01, 0.0000e+00],
         [5.6268e-36, 5.7593e-43]]])


In [25]:
# expand 함수
x=torch.FloatTensor([[[1,2]],[[3,4]]])
y=x.expand(2,3,2)

print(y)
print(y.size())

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])


In [26]:
y = torch.cat([x] * 3,dim=1)

In [27]:
# Random Permutation 함수
x=torch.randperm(10)
print(x)
print(x.size())

tensor([9, 2, 6, 8, 4, 0, 3, 1, 5, 7])
torch.Size([10])


In [28]:
# Argument Max 함수
x=torch.randperm(3**3).reshape(3,3,-1)
print(x)
print(x.size())

tensor([[[11, 13, 19],
         [18, 21,  1],
         [ 9, 23,  4]],

        [[16, 25, 15],
         [ 3,  2, 24],
         [14, 20, 26]],

        [[12, 22,  8],
         [ 5, 17,  0],
         [ 7,  6, 10]]])
torch.Size([3, 3, 3])


In [29]:
y=x.argmax(dim=-1)
print(y)
print(y.size())

tensor([[2, 1, 1],
        [1, 2, 2],
        [1, 1, 2]])
torch.Size([3, 3])


In [30]:
# Top-k 함수
values,indices=torch.topk(x,k=1,dim=-1)
print(values.size())
print(indices.size())

print("\n")
_,indices=torch.topk(x,k=2,dim=-1)
print(indices.size())

torch.Size([3, 3, 1])
torch.Size([3, 3, 1])


torch.Size([3, 3, 2])


In [31]:
target_dim=-1
values,indices=torch.topk(x,k=x.size(target_dim),largest=True)
print(values)

tensor([[[19, 13, 11],
         [21, 18,  1],
         [23,  9,  4]],

        [[25, 16, 15],
         [24,  3,  2],
         [26, 20, 14]],

        [[22, 12,  8],
         [17,  5,  0],
         [10,  7,  6]]])


In [32]:
# Marked Fill 함수
x=torch.FloatTensor([i for i in range(3**2)]).reshape(3,-1)
print(x)
print(x.size())

# Boolean Tensor
mask = x > 4
print(mask)

# masked_fill 수행
y = x.masked_fill(mask,value=-1)
print(y)

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
torch.Size([3, 3])
tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]])


In [33]:
# Ones & Zeros 함수
print(torch.ones(2,3))
print(torch.zeros(2,3))

# ones_like, zeros_like 함수
x=torch.FloatTensor([[1,2,3],[4,5,6]])
print("\n")
print(x.size())
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


torch.Size([2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
