In [1]:
import torch
x=torch.FloatTensor([[1,2],[3,4]]).requires_grad_(True)

In [2]:
x1=x+2
print(x1)

tensor([[3., 4.],
        [5., 6.]], grad_fn=<AddBackward0>)


In [3]:
x2=x-2
print(x2)

tensor([[-1.,  0.],
        [ 1.,  2.]], grad_fn=<SubBackward0>)


In [5]:
x3=x1*x2
print(x3)

tensor([[-3.,  0.],
        [ 5., 12.]], grad_fn=<MulBackward0>)


In [6]:
y=x3.sum()
print(y)

tensor(14., grad_fn=<SumBackward0>)


In [7]:
y.backward()

In [9]:
print(x.grad)

tensor([[2., 4.],
        [6., 8.]])


In [10]:
x3.detach_()

tensor([[-3.,  0.],
        [ 5., 12.]])